# Generated by Django 3.1.6 on 2021-02-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='code',
            new_name='code_challenge',
        ),
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
    ]
